config/routes.rb
Rails.application.routes.draw do
  root to:"homes#top"
  
scope module: :publics do
    
    devise_for :users
    
    resources :users, only: [:index,:show,:edit,:update] do
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    end
    
    resources :groups, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
      get "join" => "groups#join"
      delete "all_destroy" => 'groups#all_destroy'
    end
    
    get 'chat/:id' => 'chats#show', as: 'chat'
    resources :chats, only: [:create]
    
  end

  devise_for :admins, only: [:sessions, :password], :controllers => {
    :sessions => 'admins/sessions'
  }
  
  namespace :admins do
    
    resources :users, only: [:index,:show,:edit,:update]
    
    
    resources :groups, only: [:index,:show,:edit,:destroy,:update]
    
    resources :groups, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
      delete "all_destroy" => 'groups#all_destroy'
    end
  
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :chat_rooms
    has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image_id
  def get_image_id
    (image_id.attached?) ? image_id : 'no_image.jpg'
  end
end

app/controllers/admins/groups_controller.rb
class Admins::GroupsController < ApplicationController
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/publics/chats_controller.rb
class Publics::ChatsController < ApplicationController
    before_action :authenticate_user!
    def show
        @user = User.find(params[:id])
        rooms = current_user.user_rooms.pluck(:room_id)
        user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
        
        unless user_rooms.nil?
            @room = user_rooms.room
        else
            @room = Room.new
            @room.save
            UserRoom.create(user_id: @user.id, room_id: @room.id)
            UserRoom.create(user_id: current_user.id, room_id: @room.id)
        end
        
        @chats = @room.chats.order(created_at: :desc).page(params[:page])
        @chat = Chat.new(room_id: @room.id)
    end

    def create
        @chat = current_user.chats.new(chat_params)
        @chat.save
        @chats = @chat.room.chats.order(created_at: :desc).page(params[:page])

        # @chat.create_notification_dm!(current_user)

    end
    
    private
    def chat_params
        params.require(:chat).permit(:message, :room_id)
    end
end

app/controllers/publics/groups_controller.rb
class Publics::GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @group = Group.new
  end
  
  def index
    # @groups = Group.order("group.user_groups.count(user_id) desc").page(params[:page])
    groups =  Group.includes(:user_groups).sort {|a,b| b.user_groups.size <=> a.user_groups.size}
    @groups = Kaminari.paginate_array(groups).page(params[:page])
  end

  def show
    @group = Group.find(params[:id])
    @users = @group.users.page(params[:page])
  end
    
  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end
  
  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end
  
  def all_destroy
    @group = Group.find(params[:group_id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:title, :introduction, :image_id)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/controllers/publics/users_controller.rb
class Publics::UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_correct_user, only: [:edit, :update]
    
    def index
        @users = User.page(params[:page])
    end

    def show
        @user = User.find(params[:id])
        @posts = @user.posts
    end

    def edit
        @user = User.find(params[:id])
    end
  
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user), notice: "You have updated user successfully."
        else
            render 'edit'
        end
    end
  
    def withdrawal
        @user = User.find(params[:id])
        @user.update(is_deleted: true)
        reset_session
        flash[:notice] = "退会処理を実行いたしました"
        redirect_to root_path
    end
  
    private
  
    def user_params
        params.require(:user).permit(:nickname, :name, :birthdate, :image_id, :email, :password, :introduction )
    end
    
    def ensure_correct_user
        @user = User.find(params[:id])
        unless @user == current_user
            redirect_to user_path(current_user)
        end
    end
end

app/helpers/admins/groups_helper.rb
module Admins::GroupsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/chats_helper.rb
module Publics::ChatsHelper
end

app/helpers/publics/groups_helper.rb
module Publics::GroupsHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/admins/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <h2>Users</h2>
        <%= render 'admins/users/index',users: @users %>
    </div>
</div>

app/views/admins/users/show.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User</h2>
            <%= render 'admins/users/user', user: @user %>
            <div class='row'>
                <%= form_with model:@user, url: admins_user_path, method: :PATCH, local:true do |f| %>
                   <div class='col-12'><%= f.label :会員ステータス %></div>
                    <div class='col-12'>
                        <%= f.radio_button :is_deleted, false, checked: true %>
                        <%= f.label :is_deleted, '有効', value: false %>
                    </div>
                    <div class='col-12'>
                        <%= f.radio_button :is_deleted, true %>
                        <%= f.label :is_deleted, '退会', value: true %>
                    </div>
                    <div class='col-12'><%= f.submit "変更を保存" %></div>
                <% end %>
            </div>
        </div>
        <div class='col-md-8 offset-md-1'>
            <h2>Posts</h2>
            <%= render 'admins/posts/index',posts: @posts %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yagai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publics/chats/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User</h2>
            <%= render 'publics/users/user', user: @user %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <div class="row">
                <div class="col-10">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="text-align: left; font-size: 20px;">
                                <%= @user.nickname %>
                            </th>
                            <th style="text-align: right; font-size: 20px;">
                                <%= current_user.nickname %>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="message">
                        <%= render 'room', chats: @chats %>
                    </tbody>
                </table>
                <%= paginate @chats %>
                <%= render 'form', chat: @chat %>
            </div>
        </div>
    </div>
</div>

app/views/publics/groups/_from.html.erb
<%= form_with model: group, local: true do |f| %>

  <%= render "publics/shared/error_messages", resource: group %>

  <div class="form-group">
    <%= f.label :名前 %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :説明文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :表示画像 %>
    <%= f.file_field :image_id, accept: 'image/*', class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/publics/groups/_index.html.erb
<div class="card-list-container">
  <div class="row">
    <% @groups.each do |group| %>
    <div class="col-6">
        <div class="card w-60 mx-auto mt-4 shadow-lg">
          <%= link_to group do %>
            <%= image_tag group.get_image_id, class:"card-img-top" %>
          <% end %>
          <div class="card-body">
            <div class="row">
              <div class="col-8">
                <h3><%= link_to group.title, group_path(group) %></h3>
              </div>
              <div class="col-4">
                <i class="fas fa-users"></i><%= group.user_groups.count(:user_id) %>
              </div>
              <div class="col-12">
                <div class="card-text">
                  <p>
                    <%= group.introduction %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= paginate groups %>

app/views/publics/groups/edit.html.erb
 <div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>編集</h1>
   <%= render 'form', group: @group %>
  </div>
 </div>
</div>

app/views/publics/groups/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'searches/search', range: Group %>
            <%=link_to new_group_path, class:'btn btn-outline-secondary btn-block mt-3' do %>
                <i class="fas fa-plus"></i>作成する
            <% end %>
        </div>
        <div class='col-md-7 offset-md-1'>
            <h2>カテゴリ</h2>
            <%= render 'index', groups: @groups %>
        </div>
    </div>
</div>

app/views/publics/groups/new.html.erb
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>新規カテゴリ作成</h1>
   <%= render 'form', group: @group %>
  </div>
 </div>
</div>

app/views/publics/groups/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row mt-5'>
        <div class='col-md-5'>
            <table class='table'>
                <tr>
                    <th>
                        <h2><%= @group.title %></h2>
                        <%= image_tag @group.get_image_id,  class:"card-img-top" %>
                        <th></th>
                    </th>
                </tr>
                <tr>
                    <th>
                        紹介文<br>
                        <%= @group.introduction %></th>
                    <th></th>
                </tr>
                <tr>
                    <% if @group.owner_id == current_user.id %>
                        <th>
                            <%= link_to edit_group_path(@group) do %>
                            <i class="fas fa-cogs"></i>
                            <% end %>
                        </th>
                        <th>
                            <%= link_to group_all_destroy_path(@group), method: :delete, data: { confirm: '本当に消しますか？' } do %>
                                <i class="fas fa-trash-alt"></i>
                            <% end %>
                        </th>
                    <% elsif @group.users.include?(current_user) %>
                        <th><%= link_to 'フォロー中', group_path(@group), method: :delete %></th>
                    <% else %>
                        <th><%= link_to 'フォロー', group_join_path(@group) %></th>
                    <% end %>
                </tr>
            </table>
        </div>
        <div class='col-md-7'>
            <%= render 'publics/users/index' ,users: @users %>
        </div>
    </div>
</div>

app/views/publics/users/_from.html.erb
<div class='row'>
  <% if current_user != user %>
    <div id="follow_btn_<%= user.id %>", class="btn btn-outline-secondary btn-block"><%= render "publics/relationships/btn",user: user %></div>
  <% else %>
    <%= link_to user_path(user), class: "btn btn-outline-secondary btn-block user_#{user.id}" do %>
      <i class="fas fa-user"></i>マイページ
    <% end %>
    <%= link_to new_post_path, class: "btn btn-outline-secondary btn-block mt-2" do %>
     <i class="fas fa-plus"></i>新規投稿
    <% end %>
  <% end %>
</div>

app/views/publics/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>ニックネーム</th>
      <th>紹介文</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <% if current_user != user %>
       <% if user.is_deleted == false %>
          <tr>
            <td><%= image_tag user.get_image_id, size: '100x100',class:'rounded-circle' %></td>
            <td><%= user.nickname %></td>
            <td><%= user.introduction %></td>
            <td id="follow_btn_<%= user.id %>"><%= render "publics/relationships/btn",user: user %></td>
            <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
    <%= paginate users %>
  </tbody>
</table>

app/views/publics/users/_info.html.erb
<% if current_user == user %>
    <%= link_to edit_user_path(user), class:'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-cogs"></i>編集
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete, class:'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-sign-out-alt"></i>ログアウト
    <% end %>
    <%= link_to notifications_path, class:'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-bell"></i>通知
    <% end %>
<% else %>
    <div id="follow_btn_<%= user.id %>", class="btn btn-outline-secondary btn-block">
        <%= render "publics/relationships/btn",user: user %>
    </div>
    <%= link_to chat_path(user.id), class:'btn btn-outline-secondary btn-block' do %>
        <i class="fab fa-rocketchat"></i> chatを始める
    <% end %>
<% end %>

app/views/publics/users/_post.html.erb
<!--<div class="card-list-container">-->
  <% posts.each do |post| %>
    <div class="card w-60 mx-auto mt-4 shadow-lg">
      <% if post.image_id.present?%>
        <%= link_to post do %>
          <%= image_tag post.image_id, class:"card-img-top" %>
        <% end %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= link_to user_path(post.user) do%>
              <%= image_tag post.user.get_image_id, size: '50x50', class:"mt-3 rounded-circle" %>
            <% end %>
          </div>
          <div class="col-10">
            <div class="card-text">
              <p><%= post.text %></p>
            </div>
            <div class="row">
              <div class="col-md-2", id="favorite_buttons_<%= post.id %>"><%= render 'publics/post_favorites/favorite' ,post: post %></div>
              <div class="col-md-4", id="comments_count"><%= render 'publics/post_comments/comment_count' ,post: post %></div>
              <div class="col-md-2 offset-md-4">
                <%= link_to "show", post %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<!--</div>-->

app/views/publics/users/_user.html.erb
<table class='table'>
  <tr>
    <th><%= image_tag user.get_image_id, size:'100x100', class:'rounded-circle' %><br>
	  <%= user.nickname %></th>
	  <th></th>
  </tr>
  <tr>
	  <th>紹介文<br>
	   <%= user.introduction %></th>
	   <th></th>
  </tr>
  <tr>
    <th>フォロー</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>フォロワー</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

app/views/publics/users/edit.html.erb
 <div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <%= render "publics/shared/error_messages", resource: @user %>
        <div class="form-group">
          <%= f.label :ニックネーム %>
          <%= f.text_field :nickname, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :名前 %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :誕生日 %>
          <%= f.date_select :birthdate, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :画像 %>
          <%= f.file_field :image_id, accept: 'image/*', class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-secondary'%>
        </div>
      <% end %>
      <%= link_to '退会',user_unsubscribe_path(@user), class: 'btn btn-danger' %>
    </div>
  </div>
</div>  

app/views/publics/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <%= render 'searches/search', range: User %>
            <h2 class="mt-1">User</h2>
            <%= render 'publics/users/user', user: current_user %>
            <%= render 'publics/users/form', user: current_user %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <h2>Users</h2>
            <%= render 'index',users: @users %>
        </div>
    </div>
</div>

app/views/publics/users/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User</h2>
            <%= render 'publics/users/user', user: @user %>
            <%= render 'info', user: @user %>
            
        </div>
        <div class='col-md-8 offset-md-1'>
            <h2>投稿</h2>
            <%= render 'post',posts: @posts %>
        </div>
    </div>
</div>

app/views/publics/users/unsubscribe.html.erb
<h2>退会お手続き</h2>
 <p>
   退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
   再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
   本当に退会してよろしいですか？
 </p>
  <%= link_to "退会する", user_withdrawal_path, method: :patch, data: { confilm: "本当に退会しますか？" }, class: 'btn btn-danger' %>
  <%= link_to "退会しない", user_path, class: 'btn btn-success' %>